@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package bluemonster122.mods.simplerandomstuff.reference;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;

