modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
    modId="simplyrandom"
    version="${file.jarVersion}"
    displayName="Simply Random"
    credits="Myself for the newfound motivation"
    authors="LuHeGi"
    description="""
    A mod comprised of random things that I've created for fun.
    """

[[dependencies.simplyrandom]]
    modId="forge"
    mandatory=true
    versionRange="[31.2,)"
    order="NONE"
    side="BOTH"

[[dependencies.simplyrandom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"