modLoader="javafml"
loaderVersion="[28,)"
#issueTrackerURL=""
[[mods]]
    modId="simplyrandom"
    version="${file.jarVersion}"
    displayName="Simply Random"
#    updateJSONURL=""
#    displayURL=""
    logoFile=""
    credits=""
    authors="LuHeGi"
    description='''Simple little mod filled with simple little things. :)'''
[[dependencies.lgcore]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.79,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lgcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
