@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package bluemonster.simplerandomstuff;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;

