@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package bluemonster.simplerandomstuff.reference;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;

